"""Replay study: would the campaign loop have pointed at the winner earlier?

Protocol, fixed before looking at results: within the Al-Co-Cr-Fe-Ni
palette, the Borg hardness records are replayed in publication-year
order. The campaign starts cold (no warm start, because the warm-start
pool IS this data), observes each year's alloys as they were published,
and after every year suggests a batch of five. The question is when a
suggestion first lands within an L1 mole-fraction distance of 0.2 (two
lattice steps at the 0.1 resolution used here) of the eventual
highest-hardness alloy in the palette, versus the year that alloy was
actually published. The corpus-domain constraint is switched off in the
replay because the fitted domain model summarizes the corpus including
years the replay has not reached yet.

Reported honestly either way, including the no-lead outcome. One replay
on one family is an anecdote with a fixed protocol, not a validation of
the loop; it is the study this data can support without importing
anyone else's campaign.

    PYTHONPATH=src python tools/campaign_replay.py
"""

from __future__ import annotations

import datetime
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from hea_bench import __version__ as _hea_bench_version  # noqa: E402
from hea_bench.design import DomainConstraint  # noqa: E402
from hea_bench.design.campaign import COLD_START_FLOOR, Campaign  # noqa: E402
from hea_bench.properties.borg import hardness_records  # noqa: E402

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_MD = REPO_ROOT / "docs" / "campaign-replay.md"

PALETTE = ["Al", "Co", "Cr", "Fe", "Ni"]
STEP = 0.1
HIT_L1 = 0.2
BATCH = 5


def _l1(a: dict, b: dict) -> float:
    keys = set(a) | set(b)
    return sum(abs(a.get(key, 0.0) - b.get(key, 0.0)) for key in keys)


def main() -> int:
    try:
        import sklearn  # noqa: F401
    except ImportError:
        print('needs scikit-learn: pip install -e ".[properties]"', file=sys.stderr)
        return 2

    palette_set = set(PALETTE)
    records = [
        record
        for record in hardness_records()
        if set(record.composition) <= palette_set and record.year is not None
    ]
    records.sort(key=lambda record: (record.year, record.formula_raw))
    winner = max(records, key=lambda record: record.value)

    years = sorted({record.year for record in records})
    campaign = Campaign(
        "hardness",
        PALETTE,
        (DomainConstraint(in_domain=None),),
        seed=0,
        step=STEP,
        n_elements=(4, 5),
        warm_start=False,
    )

    rows = []
    first_hit_year = None
    for year in years:
        for record in records:
            if record.year == year:
                campaign.observe(
                    record.composition, record.value, processing=record.processing
                )
        n_seen = campaign.n_informative()
        if n_seen < COLD_START_FLOOR:
            rows.append((year, n_seen, None))
            continue
        if winner.year is not None and year >= winner.year:
            break
        suggestions = campaign.suggest(n=BATCH)
        distance = min(_l1(s.composition, winner.composition) for s in suggestions)
        rows.append((year, n_seen, distance))
        if distance <= HIT_L1 and first_hit_year is None:
            first_hit_year = year

    lead = (winner.year - first_hit_year) if first_hit_year is not None else None
    lines = [
        "# Campaign replay on the Al-Co-Cr-Fe-Ni hardness record",
        "",
        f"Generated by `tools/campaign_replay.py` with hea-bench "
        f"{_hea_bench_version} on {datetime.date.today().isoformat()}; protocol "
        f"in the tool docstring (batch {BATCH}, EI, step {STEP}, hit radius "
        f"L1 {HIT_L1}, cold start, publication-year order).",
        "",
        f"{len(records)} palette alloys with a publication year replay across "
        f"{len(years)} years. The eventual hardest alloy is "
        f"{winner.formula_raw} (HV {winner.value:.0f}, "
        f"{winner.processing or 'unrecorded processing'}, published "
        f"{winner.year}).",
        "",
        "| year observed through | informative rows | min L1 from that round's "
        "suggestions to the eventual winner |",
        "|---:|---:|---:|",
    ]
    for year, n_seen, distance in rows:
        shown = f"{distance:.2f}" if distance is not None else "(below cold-start floor)"
        lines.append(f"| {year} | {n_seen} | {shown} |")
    lines += [
        "",
        "## Outcome",
        "",
        (
            f"The loop first suggested within the hit radius of the eventual "
            f"winner after observing data through {first_hit_year}, "
            f"{lead} years before the winner's own publication year."
            if lead is not None and lead > 0
            else (
                f"The loop first reached the hit radius in {first_hit_year}, "
                f"which gives no lead over the winner's publication year "
                f"({winner.year})."
                if first_hit_year is not None
                else (
                    f"The loop never suggested within the hit radius before "
                    f"the winner's publication year ({winner.year}). That is "
                    f"the honest outcome of this replay."
                )
            )
        ),
        "",
        "Read with the stated limits: one family, one ordering, a lattice "
        "that cannot express every published stoichiometry exactly, and a "
        "surrogate whose model card documents a wide honest error. The "
        "replay checks that the loop's mechanics point in a sensible "
        "direction on real history; it does not demonstrate discovery.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
