"""Retrospective recovery study for the composition search.

Question, stated before the answer: if the search had been run with
constraints matching a heavily studied design space, would it have
surfaced the alloys experimentalists actually made and measured, and
where do those alloys sit relative to the returned front? Two palettes
are studied, both fully inside the Borg hardness data: the Al-Co-Cr-Fe-Ni
family (the classic hardness-versus-density trade space) and the
Mo-Nb-Ta-V-W refractory family. The honest outcome is reported either
way, including front members no one has synthesized (which are
suggestions, not validated predictions) and measured alloys the front
rejects (dominated, or filtered by a constraint).

Needs the properties extra and a built corpus:

    PYTHONPATH=src python tools/design_recovery.py
"""

from __future__ import annotations

import datetime
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from hea_bench import __version__ as _hea_bench_version  # noqa: E402
from hea_bench.design import Maximize, Minimize, search  # noqa: E402
from hea_bench.properties import predict_property  # noqa: E402
from hea_bench.properties.borg import hardness_records  # noqa: E402

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_MD = REPO_ROOT / "docs" / "design-recovery.md"

PALETTES = {
    "Al-Co-Cr-Fe-Ni": ["Al", "Co", "Cr", "Fe", "Ni"],
    "Mo-Nb-Ta-V-W": ["Mo", "Nb", "Ta", "V", "W"],
}
STEP = 0.05
TOP_N = 10


def _l1(a: dict, b: dict) -> float:
    keys = set(a) | set(b)
    return sum(abs(a.get(key, 0.0) - b.get(key, 0.0)) for key in keys)


def _rank(values: list[float]) -> list[float]:
    order = sorted(range(len(values)), key=lambda i: values[i])
    ranks = [0.0] * len(values)
    for position, index in enumerate(order):
        ranks[index] = float(position)
    return ranks


def _spearman(a: list[float], b: list[float]) -> float:
    ranks_a, ranks_b = _rank(a), _rank(b)
    n = len(a)
    mean = (n - 1) / 2.0
    cov = sum((x - mean) * (y - mean) for x, y in zip(ranks_a, ranks_b))
    var = sum((x - mean) ** 2 for x in ranks_a)
    return cov / var if var else 0.0


def _study(name: str, palette: list[str]) -> list[str]:
    result = search(
        elements=palette,
        n_elements=(4, 5),
        objectives=(Maximize("hardness"), Minimize("density")),
        step=STEP,
        n_candidates=250,
        optimize_bound="lower",
    )

    palette_set = set(palette)
    measured = [
        record
        for record in hardness_records()
        if set(record.composition) <= palette_set and len(record.composition) >= 4
    ]
    measured.sort(key=lambda record: -record.value)

    predicted = [
        predict_property(record.composition, "hardness").value for record in measured
    ]
    correlation = _spearman(predicted, [record.value for record in measured])

    hits = []
    for record in measured[:TOP_N]:
        distance = min(
            (_l1(record.composition, candidate.composition) for candidate in result.candidates),
            default=float("inf"),
        )
        hits.append((record, distance))
    recovered = sum(1 for _record, distance in hits if distance <= 2 * STEP + 1e-9)

    lines = [
        f"## Palette {name}",
        "",
        f"Search: n_elements 4 to 5, step {STEP}, objectives maximize hardness "
        f"(conservative lower interval end) and minimize density, domain "
        f"constraint on. {result.n_evaluated} lattice points evaluated, "
        f"{result.n_feasible} feasible, front size {result.n_front}.",
        "",
        f"{len(measured)} measured alloys from the Borg hardness records live "
        f"inside this palette (4 or 5 elements). Rank correlation between the "
        f"surrogate's point predictions and the measured hardness over those "
        f"alloys: Spearman rho = {correlation:.2f}. Of the {min(TOP_N, len(measured))} "
        f"hardest measured alloys, {recovered} sit within two lattice steps "
        f"(L1) of a front member.",
        "",
        "| measured alloy | HV | processing | L1 distance to nearest front member |",
        "|---|---:|---|---:|",
    ]
    for record, distance in hits:
        shown = f"{distance:.2f}" if distance != float("inf") else "n/a"
        lines.append(
            f"| {record.formula_raw} | {record.value:.0f} | "
            f"{record.processing or '-'} | {shown} |"
        )
    lines.append("")
    return lines


def main() -> int:
    try:
        import sklearn  # noqa: F401
    except ImportError:
        print('needs scikit-learn: pip install -e ".[properties]"', file=sys.stderr)
        return 2

    lines = [
        "# Retrospective recovery: does the search surface what was actually made?",
        "",
        f"Generated by `tools/design_recovery.py` with hea-bench "
        f"{_hea_bench_version} on {datetime.date.today().isoformat()}.",
        "",
        "Protocol: run the search over a heavily studied palette with the "
        "hardness-versus-density objectives, then place the alloys "
        "experimentalists measured (Borg hardness records inside the palette) "
        "relative to the returned front. Two readings matter and they are "
        "different: whether the hardest measured alloys are recovered near "
        "the front (retrospective sanity), and whether the surrogate ranks "
        "the measured alloys in the measured order (Spearman rho below; the "
        "model card's error analysis applies). Front members with no "
        "measured neighbor are suggestions the study never tested, not "
        "validated predictions, and a measured alloy far from the front is "
        "not refuted, it may simply be dominated on these two objectives or "
        "sit off the lattice.",
        "",
    ]
    for name, palette in PALETTES.items():
        lines += _study(name, palette)

    lines += [
        "## Reading this honestly",
        "",
        "Recovery here is a weak, necessary check, not a validation of the "
        "search as a discovery engine: the surrogate was trained on data "
        "that includes these families, so finding their known good alloys "
        "again is expected rather than impressive. The informative failure "
        "mode is the opposite one, a hard measured alloy the front misses, "
        "and the tables above report exactly that distance for the top ten "
        "in each palette. The search remains a screening aid whose value is "
        "receipts and constraint handling, not oracle ranking.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
