"""Measure empirical conformal coverage on the corpus and write the doc.

The study itself is :func:`hea_bench.uncertainty.coverage.coverage_study`,
whose docstring states the design: a nested cross-validation over the
frozen system split that tests exactly the procedure the released
predictor uses. This script runs it for both tasks and writes
``docs/uncertainty-coverage.md``: a summary table per task (the shape
``tests/test_conformal.py`` reads, whose in-domain and out-of-domain
columns ``MEASURED_COVERAGE`` must match) and the full table of every
result group with its alloy-system count, fold-to-fold standard error
and mean set size. Nothing here characterizes any published model or
any other tool.

Takes about two minutes. Needs the benchmark extra:

    PYTHONPATH=src python tools/uncertainty_coverage.py
"""

from __future__ import annotations

import datetime
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from hea_bench import __version__ as _hea_bench_version  # noqa: E402
from hea_bench.uncertainty.coverage import (  # noqa: E402
    ALPHAS,
    FOREST_TREES,
    GROUPS,
    SEED,
    coverage_study,
)

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_MD = REPO_ROOT / "docs" / "uncertainty-coverage.md"

LABELS = {
    "all": "every alloy",
    "in_domain": "inside the dataset's range",
    "out_of_domain": "outside the dataset's range",
    "fewer_than_four": "fewer than four elements",
    "four_or_more": "four or more elements",
    "four_or_more_one_element_from_training": "four or more, one element from a training system",
    "four_or_more_farther": "four or more, farther from every training system",
}


def _rate(value) -> str:
    return "n/a" if value is None else f"{value:.3f}"


def _format_task(study: dict) -> list[str]:
    by_alpha = {level["alpha"]: level["groups"] for level in study["levels"]}
    lines = [
        f"## Task: {study['task']}",
        "",
        f"{study['n_rows']} descriptor-finite alloys. Across the five held-out "
        f"folds the domain model flagged {study['n_out_of_domain']} as outside "
        f"the dataset's range, {study['n_out_of_domain_binaries']} of them binary.",
        "",
        "| nominal coverage | rows | empirical (overall) | empirical (in domain) | "
        "empirical (out of domain) | set size (in) | set size (out) |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for alpha in ALPHAS:
        groups = by_alpha[alpha]
        overall, inside, outside = groups["all"], groups["in_domain"], groups["out_of_domain"]
        lines.append(
            f"| {1 - alpha:.0%} | {overall['n']} | {_rate(overall['coverage'])} | "
            f"{_rate(inside['coverage'])} | {_rate(outside['coverage'])} | "
            f"{inside['mean_set_size']:.2f} | {outside['mean_set_size']:.2f} |"
        )
    lines += [
        "",
        "Every group, with its alloy-system count and the standard error of "
        "coverage across the five folds:",
        "",
        "| nominal | group | alloys | systems | coverage | fold SE | mean set size |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for alpha in ALPHAS:
        for group in GROUPS:
            cell = by_alpha[alpha][group]
            se = "n/a" if cell["fold_se"] is None else f"{cell['fold_se']:.3f}"
            size = "n/a" if cell["mean_set_size"] is None else f"{cell['mean_set_size']:.2f}"
            lines.append(
                f"| {1 - alpha:.0%} | {LABELS[group]} | {cell['n']} | {cell['n_systems']} | "
                f"{_rate(cell['coverage'])} | {se} | {size} |"
            )
    lines.append("")
    return lines


def main() -> int:
    try:
        import sklearn  # noqa: F401
    except ImportError:
        print(
            "this study fits the baseline random forest; install the pinned "
            'version with: pip install -e ".[benchmark]"',
            file=sys.stderr,
        )
        return 2

    studies = [coverage_study(task) for task in ("single_vs_multi", "phase4")]

    lines = [
        "# Empirical conformal coverage on corpus v0.1.0",
        "",
        f"Generated by `tools/uncertainty_coverage.py` with hea-bench "
        f"{_hea_bench_version} on {datetime.date.today().isoformat()}; random "
        f"forest with {FOREST_TREES} trees, seed {SEED}, scored on the frozen "
        f"system folds.",
        "",
        "The study tests the procedure the released predictor uses. Each "
        "fold of the frozen system split is held out in turn, and the other "
        "four folds stand in for the whole corpus. Their calibration scores "
        "come from cross-validation among those four folds, so every score "
        "comes from a forest that never saw the alloy's system. A forest "
        "refit on all four folds predicts the held-out fold, and the sets "
        "are calibrated separately for alloys with fewer than four elements "
        "and with four or more. A domain model fitted on the same four folds "
        "flags each held-out alloy as inside or outside the dataset's range. "
        "Every held-out system is unseen, so the study measures coverage on "
        "new alloy systems, the case a user meets when exploring.",
        "",
    ]
    for study in studies:
        lines += _format_task(study)
    lines += [
        "## Reading the tables",
        "",
        "Mean set size is the average number of labels in the returned "
        "prediction set. A method can always reach nominal coverage by "
        "returning every label, so coverage is only meaningful next to set "
        "size. A set holding every label is the calibrated way of saying the "
        "model cannot rule any out. The fold standard error is the spread of "
        "coverage across the five held-out folds, which differ in size "
        "because each holds whole systems. These numbers describe this "
        "package's models on this corpus and nothing else.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
