"""Measure empirical conformal coverage on the corpus and write the doc.

Design, stated up front because the numbers only mean something under
it: for each grouped fold of corpus v0.1.0 (both tasks), the training
rows are split family-grouped into proper-train (about 80 percent) and
calibration (about 20 percent), a random forest (300 trees, seed 0, the
baseline configuration) is fitted on the proper-train descriptor
matrix, a ConformalClassifier is calibrated on the calibration rows,
and prediction sets at nominal 80, 90, and 95 percent are scored on the
held-out fold. A DomainModel fitted on the proper-train rows only
classifies every test row as in or out of domain, and coverage is
reported overall and per flag, together with mean set sizes.

The grouped split makes test families unseen by construction, so this
study measures the assumption under strain on purpose. The measured
pattern, verified on the first grouped fold before being written down:
the flagged out-of-domain population is almost entirely far-from-HEA
binary compositions that the model predicts confidently and mostly
correctly (above-nominal coverage, slightly smaller sets), while the
coverage shortfall concentrates in in-domain-flagged rows where an
unseen family lies close to the training cloud and is predicted
confidently and wrongly. Nothing here characterizes any published
model or any other tool.

Runs a few minutes (descriptor recomputation dominates). Needs the
benchmark extra:

    PYTHONPATH=src python tools/uncertainty_coverage.py
"""

from __future__ import annotations

import datetime
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from hea_bench import __version__ as _hea_bench_version  # noqa: E402
from hea_bench.uncertainty.coverage import (  # noqa: E402,F401  (re-exported for figure scripts)
    ALPHAS,
    CALIBRATION_FRACTION,
    FOREST_TREES,
    SEED,
    coverage_study,
)
from hea_bench.uncertainty.coverage import (  # noqa: E402,F401
    family_grouped_calibration_split as _family_grouped_calibration_split,
)

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_MD = REPO_ROOT / "docs" / "uncertainty-coverage.md"


def _run_task(task: str) -> dict:
    """The study through the library, in the table shape this script writes."""
    study = coverage_study(task)
    table = {}
    for level in study["levels"]:
        groups = level["groups"]
        table[level["alpha"]] = {
            bucket: [groups[group]["covered"], groups[group]["n"], groups[group]["set_size_sum"]]
            for bucket, group in (("overall", "all"), ("in", "in_domain"), ("out", "out_of_domain"))
        }
    return {"task": task, "n_rows": study["n_rows"], "n_out": study["n_out_of_domain"], "table": table}


def _format_task(result: dict) -> list[str]:
    lines = [
        f"## Task: {result['task']}",
        "",
        f"{result['n_rows']} descriptor-finite rows; {result['n_out']} test-time "
        f"rows were flagged out of domain by the proper-train DomainModel "
        f"across the five grouped folds.",
        "",
        "| nominal coverage | rows | empirical (overall) | empirical (in domain) | "
        "empirical (out of domain) | set size (in) | set size (out) |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for alpha in ALPHAS:
        table = result["table"][alpha]
        overall, inside, outside = table["overall"], table["in"], table["out"]

        def rate(cell):
            return f"{cell[0] / cell[1]:.3f}" if cell[1] else "n/a"

        def size(cell):
            return f"{cell[2] / cell[1]:.2f}" if cell[1] else "n/a"

        lines.append(
            f"| {1 - alpha:.0%} | {overall[1]} | {rate(overall)} | {rate(inside)} | "
            f"{rate(outside)} | {size(inside)} | {size(outside)} |"
        )
    lines.append("")
    return lines


def main() -> int:
    try:
        import sklearn  # noqa: F401
    except ImportError:
        print(
            "this study fits the baseline random forest; install the pinned "
            'version with: pip install -e ".[benchmark]"',
            file=sys.stderr,
        )
        return 2

    results = [_run_task(task) for task in ("single_vs_multi", "phase4")]

    lines = [
        "# Empirical conformal coverage on corpus v0.1.0",
        "",
        f"Generated by `tools/uncertainty_coverage.py` with hea-bench "
        f"{_hea_bench_version} on {datetime.date.today().isoformat()}; random "
        f"forest with {FOREST_TREES} trees, seed {SEED}, family-grouped "
        f"calibration split of {CALIBRATION_FRACTION:.0%}, scored on the frozen "
        f"grouped folds.",
        "",
        "Split conformal prediction guarantees marginal coverage when "
        "calibration and test rows are exchangeable. The grouped split makes "
        "test families unseen by construction, so this study measures the "
        "guarantee under deliberate strain, and the table reports what that "
        "strain does. Overall coverage lands a few points under nominal, and "
        "the shortfall sits in the rows flagged in domain: unseen families "
        "close to the training cloud in descriptor space, predicted "
        "confidently and sometimes wrongly. The rows flagged out of domain "
        "behave differently in this corpus. They are almost entirely binary "
        "compositions whose element pairs sit far from the multi-principal "
        "families the corpus is built around (on the first grouped fold, 110 "
        "of 121 flagged rows are binaries), the model's predictions there "
        "are confident and mostly right, and their empirical coverage sits "
        "above nominal with slightly smaller sets. The flag therefore "
        "separates a structurally different population rather than marking "
        "where the classifier fails, and the residual near-domain "
        "extrapolation risk it cannot remove is exactly what the paired "
        "interpolative versus extrapolative protocol quantifies. Read the "
        "flag, the set size, and the gap together. These numbers describe "
        "this package's models on this corpus and nothing else.",
        "",
    ]
    for result in results:
        lines += _format_task(result)
    lines += [
        "## Reading the table",
        "",
        "Mean set size is the average number of labels in the returned "
        "prediction set. A method can always reach nominal coverage by "
        "returning every label, so coverage is only meaningful next to set "
        "size; a full-class set is the calibrated way of saying the model "
        "does not know. Out-of-domain rows are typically fewer, so their "
        "empirical rates carry wider sampling noise.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
